version: '2'
services:
    redis:
        image: redis
        container_name: redis
        restart: always
        networks:
            - pen2
    waf:
        image: pen2
        container_name: pen2
        restart: always
        ports:
            - "0.0.0.0:8008:80"
        networks:
            - pen2
        depends_on:
            - redis
networks:
    pen2:
        driver: bridge
        ipam:
            config:
                - subnet: 192.168.88.0/24
